apiVersion: skaffold/v4beta5
#apiVersion: skaffold/v3alpha1
kind: Config
#manifests:
#  rawYaml:
#  - service.yaml
manifests:
  kustomize:
    paths:
      - overlays/dev
  #hooks:
  #    before:
  #      - host:
  #          command: 
  #            ["sh", "-c", "gcloud run services delete quotes-front --region=us-central1 --quiet | cat"]
  #              ["sh", "-c", "gcloud run deploy service.yaml --region=us-central1 --quiet"]
  #              ["sh", "-c", "gcloud run services set-iam-policy quotes-front policy.yaml --region=us-central1 --quiet"]
  #          os: [darwin, linux]
  #    after:
  #      - host:
  #          command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front policy.yaml --region=us-central1 --quiet"]

metadata:
  name: quotes-front
build:
# needs 2 artifacts in build phasis since reacjs env variable are changed at build time and build 
# will not occurs between dev and prod in a cloud deploy pipeline 
  artifacts:
  - image: quotes-front-dev
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        REACT_APP_BACK_URL: app.dev.gabrielbechara.com
        REACT_APP_ENV: dev
  - image: quotes-front-prod
    context: .
    docker:
      dockerfile: Dockerfile
      buildArgs:
        REACT_APP_BACK_URL: app.prod.gabrielbechara.com
        REACT_APP_ENV: prod
deploy:
  cloudrun:
    projectid: gab-devops-1
    region: us-central1
    hooks:
#      before:
#        - command: ["sh", "-c", "gcloud run services delete quotes-front --region=us-central1 --quiet | cat"]
      after:
       - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-dev policy.yaml --region=us-central1 --quiet | cat"]
#      - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]

profiles:
- name: dev
  manifests:
    kustomize:
      paths:
        - overlays/dev
  deploy:
    cloudrun:
      projectid: gab-devops-1
      region: us-central1
      hooks:
        after:
        - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-dev policy.yaml --region=us-central1 --quiet | cat"]
  customActions:
  - name: predeploy-action
    containers:
    - name: predeploy-echo
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", 'echo "this is a predeploy action"' ]
  - name: postdeploy-action
    containers:
    - name: postdeploy-echo
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", 'echo "this is a postdeploy action"' ]
    - name: postdeploy-apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      command: ["/bin/sh"]
      args: ["-c", "echo $PATH
      &&
      pwd
      &&
      ls -trail /
      &&
      echo $PROJECT 
      &&
      echo $LOCATION 
      &&
      echo $PIPELINE
      &&
      echo $RELEASE    
      &&
      echo \"CLOUD_RUN_POLICY_FILE\" > policy.json
      &&
      cat policy.json
      &&
      gcloud run services set-iam-policy quotes-front-dev policy.json --region=us-central1 --quiet | cat"]

# hooks are not used by cloud deploy, using verify instead
  verify:
  - name: apply-policy
    container:
      name: apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      command: ["/bin/sh"]
#      args: ["-c", "cat <<EOF > policy.yaml
#      bindings:
#      - members:
#        - allUsers
#        role: roles/run.invoker
#      EOF 
#      &&
      args: ["-c", "echo $PATH
      &&
      pwd
      &&
      ls -trail /
      &&
      echo $PROJECT 
      &&
      echo $LOCATION 
      &&
      echo $PIPELINE
      &&
      echo $RELEASE    
      &&
      echo \"CLOUD_RUN_POLICY_FILE\" > policy.json
      &&
      cat policy.json
      &&
      gcloud run services set-iam-policy quotes-front-dev policy.json --region=us-central1 --quiet | cat"]

- name: prod
  manifests:
    kustomize:
      paths:
        - overlays/prod
  deploy:
    cloudrun:
      projectid: gab-devops-1
      region: us-central1
      hooks:
        after:
        - command: ["sh", "-c", "gcloud run services set-iam-policy quotes-front-prod policy.yaml --region=us-central1 --quiet | cat"]
  customActions:
  - name: predeploy-action
    containers:
    - name: predeploy-echo
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", 'echo "this is a predeploy action"' ]
  - name: postdeploy-action
    containers:
    - name: postdeploy-echo
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", 'echo "this is a postdeploy action"' ]
    - name: postdeploy-apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      command: ["/bin/sh"]
      args: ["-c", "echo $PATH
      &&
      pwd
      &&
      ls -trail /
      &&
      echo $PROJECT 
      &&
      echo $LOCATION 
      &&
      echo $PIPELINE
      &&
      echo $RELEASE    
      &&
      echo \"CLOUD_RUN_POLICY_FILE\" > policy.json
      &&
      cat policy.json
      &&
      gcloud run services set-iam-policy quotes-front-prod policy.json --region=us-central1 --quiet | cat"]


# hooks are not used by cloud deploy, using verify instead
  verify:
  - name: apply-policy
    container:
      name: apply-policy
      image: gcr.io/google.com/cloudsdktool/cloud-sdk
      command: ["/bin/sh"]
      args: ["-c", "echo $PATH
      &&
      echo \"CLOUD_RUN_POLICY_FILE\" > policy.json
      &&     
      gcloud run services set-iam-policy quotes-front-prod policy.json --region=us-central1 --quiet | cat"]